name: Building crdroid

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/crdroidandroid/android.git -b 11.0
  DEVICE: m10lte
  DT_LINK: https://dumps.tadiphone.dev/dumps/redmi/viva.git -b crdroid
  DT_PATH: device/xiaomi/viva
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm-pkg p && cd p && bash setup.sh

            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j100 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK $DT_PATH --depth=1            
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && brunch $DEVICE
              zip crdroid.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*droid*
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: crdroid.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/crdroid.zip
            retention-days: 5
