name: Build recovery(twrp,shrp,pbrp)
on:
  workflow_dispatch:

env:
  # change value from:

  # A) choosing right manifest:
  # 1) manifest is required choose the compatible its depend on your current android version.
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  # 2) manifest branch same thing it depend on your current android
  BRANCH: twrp-11

  # B) Information about your device:
  # 1) every device tree use main file called twrp_/omni_****.mk use the name between .mk and omni_/twrp_ keyword
  DEVICE: X698
  # 2) device tree link
  DT_LINK: https://github.com/SA-17/android_device_infinix_Infinix-X698
  # 3) device manufacturer please you the one which used on device.mk or BoardConfig.mk 
  MANUFACTURER: infinix
  # 4) target build. depend on what you have on you phone. recovery partition: recovery or recovery in boot partition: boot
  TARGET: boot
  # 5) build type eng (recommended) , user (dont use it), userdebug (this too)
  BTYPE: eng
  # 6) Twrp type omni or twrp may depend on main file omni_/twrp_****.mk
  OT: twrp
  # end dont edit anything after this comment
  
  # C) these part and what under dont edit it
  IMAGE: image
  SYM: _

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Init the System
         uses: actions/checkout@master
                               
       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git zip
            git clone https://github.com/SA-17/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Adding and Sync source
         run: |   
             mkdir work
             cd work
             repo init -u $MANIFEST -b $BRANCH --depth=1              
             repo sync -c -j700 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK --depth=1 --single-branch device/$MANUFACTURER/$DEVICE          
             
       - name: Build recovery
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$SYM$DEVICE-$BTYPE && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET$IMAGE -j30
              zip out/target/product/recovery.zip out/target/product/$DEVICE/$TARGET.*
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: recovery for ${{ github.event.inputs.DEVICE_NAME }}
          files: work/out/target/product/recovery.zip
