name: Building Twrp

on:
  workflow_dispatch:

env:
  # twrp manifest
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
  # manifest branch
  BRANCH: twrp-9.0
  # device codename i.e: sweet mojito..
  DEVICE: m10lte
  # device tree link with branch
  DT_LINK: https://github.com/Hostfl/android_device_samsung_m10lte -b twrp-10
  # who made your phone ?
  MANUFACTURER: samsung
  # recovery partiton = recovery, else (no recovery partition): boot
  TARGET: recovery
  # dont change that
  IMAGE: image
  # depend of device tree if you see twrp_"codename".mk use twrp
  # else (omni_"codename".mk): omni
  OT: omni
  # dont change that
  SYM: _
  # output format for some reason samsung phones need a custom mkbootimg
  # which compress your recovery into .tar (default: .img / samsung + custom mkbootimg: .tar)
  FORMAT: .img

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/Hostfl/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            mkdir work
            cd work
            repo init -u $MANIFEST -b $BRANCH --depth=1
            
       - name: Sync source
         run: |          
             repo sync -c -j700 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK --depth=1 --single-branch device/$MANUFACTURER/$DEVICE          
             
       - name: Build twrp
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$SYM$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET$IMAGE -j20
              zip twrp.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/$BUILD.img

       - name: Save in artifact
         uses: actions/upload-artifact@v3
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/twrp.zip
            retention-days: 5
